_extends: github-apps-config-next
branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - 'ci/circleci: build-v16.14'
      enforce_admins: true
      restrictions:
        users: []
        teams: []
