plugins:
  - "@dotcom-tool-kit/component"
  - "./toolkit/karma"
  
hooks:
  test:local:
    - Karma
  test:ci:
    - Karma

options:
  "@dotcom-tool-kit/circleci":
    nodeVersion:
      - '18.16-browsers'
